# manual steps:
# dnf module disable nodejs -y  Install NodeJS, By default NodeJS 16 is available, We would like to enable 20 version and install this.
# dnf module enable nodejs:20 -y
# dnf install nodejs -y
# useradd expense       Add application User
# mkdir /app     Lets setup an app directory.
# Download the application code to created app directory.
# curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
# cd /app
# unzip /tmp/backend.zip
# cd /app  
# npm install   download the dependencies.
# systemctl daemon-reload  Load the service.
# systemctl start backend  Start the service.
# systemctl enable backend  Start the service.
# dnf install mysql -y   installing  mysql client.
# mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pExpenseApp@1 < /app/schema/backend.sql   Loading  Schema
# systemctl restart backend   Restart the service.




- name: configure backend server
  become: yes
  hosts: backend

  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf: # only works for Redhat family
      name: nodejs
      state: installed

  - name: create expense user
    ansible.builtin.user:
      name: expense
